import streamlit as st
import pandas as pd
from src.analysis.insights import generate_business_recommendations

def render(df: pd.DataFrame):
    if df.empty:
        st.warning("No tracking data available. Adjust constraints.")
        return
        
    st.markdown("## C-Suite AI Copilot")
    st.write("Interact natively with the underlying analytical matrix using natural language syntax. The Copilot evaluates the active filtered bounds instantaneously.")
    st.divider()

    # Initialize conversational memory cleanly
    if "messages" not in st.session_state:
        st.session_state.messages = [
            {"role": "assistant", "content": "Welcome to the Executive Interface. I am explicitly calibrated to your active temporal and geographic data filters. Ask me for a **Risk Assessment**, a **Revenue Strategy**, or command me to **Generate a Report** to instantly compile an autonomous C-Suite briefing mathematically."}
        ]

    # Render conversational tracking matrix sequentially
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # Hook absolute intercept sequences to structural stream
    if prompt := st.chat_input("Query the analytical matrix natively... (e.g., 'Generate Executive Report')"):
        
        # Lock user query layout natively
        st.chat_message("user").markdown(prompt)
        st.session_state.messages.append({"role": "user", "content": prompt})

        # Synthesize logic routing bounds tracking exact NLP constraints dynamically
        prompt_lower = prompt.lower()
        response = ""
        
        if "risk" in prompt_lower or "anomaly" in prompt_lower or "threat" in prompt_lower:
            r_group = df.groupby('Region')['Services_Revenue'].mean()
            if len(r_group) > 0:
                worst_region = r_group.idxmin()
                worst_val = r_group.min()
                global_mean = r_group.mean()
                if worst_val < global_mean * 0.8:
                    response = f"**CRITICAL SECTOR IDENTIFIED:** `{worst_region}` Services conversion is tracking {(1-(worst_val/global_mean))*100:.1f}% structurally below global network parity limits. \n\n**Action:** Re-allocate 40% of standard operational spend strictly into completely localized `{worst_region}` advertising funnels immediately natively to stabilize geometric losses."
                else:
                    response = "**Matrix Secure:** No severe autonomous regional revenue deviations physically mapped across standard global tracking boundaries."
            else:
                response = "Insufficient dimensional limits mapped to effectively calculate localized geographic anomalies securely."
                
        elif "report" in prompt_lower or "briefing" in prompt_lower or "summary" in prompt_lower:
            total_rev = df['Services_Revenue'].sum()
            total_hardware = ['iPhone_Sales', 'iPad_Sales', 'Mac_Sales', 'Wearables_Sales']
            avail = [f for f in total_hardware if f in df.columns]
            total_units = df[avail].sum().sum() if avail else 0
            
            recs = generate_business_recommendations(df)
            strat_str = "\n".join([f"- **{r['type'].upper()}**: {r['msg']}" for r in recs]) if recs else "- Maintain nominal structural trajectories flawlessly."
            
            report_content = f"""#  AUTONOMOUS EXECUTIVE BRIEFING
**Total Evaluated Software Revenue:** `${total_rev:,.1f}B`
**Total Evaluated Hardware Distributions:** `{total_units:,.1f}M Units`

### Active Algorithmic Strategic Directives:
{strat_str}

---
*Report autonomously constructed securely by the built-in Machine Learning Copilot.*
"""
            response = f"**Automated Corporate Briefing Compiled Successfully.**\n\n```markdown\n{report_content}\n```\n_Click the upper-right copy toggle inside the markdown block to export this structurally directly to your absolute clipboard limits._"
            
        elif "strategy" in prompt_lower or "maximize" in prompt_lower or "revenue" in prompt_lower or "insight" in prompt_lower:
            recs = generate_business_recommendations(df)
            if recs:
                strat_str = "\n\n".join([f"**{r['type'].upper()} LIMIT**: {r['msg']}" for r in recs])
                response = f"Here are the absolute mathematically optimized combinations actively dynamically generated by the `scikit-learn` bounding limit structures:\n\n{strat_str}"
            else:
                response = "Data matrix constraints identically are too narrow functionally to definitively systematically calculate absolute structural combinations."
        
        else:
            response = "I am strictly rigidly constrained to mathematically secure boundary operations. Please securely request an **Anomalous Risk Assessment**, an **Algorithmic Strategy**, or explicitly command a **Generated Report**."
            
        # Deliver explicit output cleanly mapping to the stream
        with st.chat_message("assistant"):
            st.markdown(response)
        st.session_state.messages.append({"role": "assistant", "content": response})
